epochs: 500
learning_rate: 0.00025
batch_size: 5
num_workers: 5

# ------------------------------- Augmentation ------------------------------- #
use_augmentation: true
augmentation:
  # crop, flip and rotate
  use_random_flip: true
  flip_probability: 0.5
  use_random_crop: true
  min_crop_size: 0.25
  use_random_rotation: true
  min_rotation: 0.05
  max_rotation: 0.95
  
  # brightness & contrast
  use_random_brightness: true
  brightness_min: 0.8
  brightness_max: 1.2
  use_random_contrast: true
  contrast_min: 0.8
  contrast_max: 1.2
  use_random_saturation: true
  saturation_min: 0.8
  saturation_max: 1.2
